plugins {
	id 'net.fabricmc.fabric-loom' version "${loom_version}"
	id 'maven-publish'
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
}

version = project.mod_version
group = project.maven_group

base {
	archivesName = project.archives_base_name
}

repositories {
    maven { url "https://maven.shedaniel.me" }
    maven {
        name = "Jared's maven"
        url = "https://maven.blamejared.com/"
    }
    maven {
        url "https://cursemaven.com"
    }
    exclusiveContent {
        forRepository {
            maven {
                name = "Modrinth"
                url = "https://api.modrinth.com/maven"
            }
        }
        filter {
            includeGroup "maven.modrinth"
        }
    }
}

fabricApi {
	configureDataGeneration {
		client = true
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_version}"

    implementation include("com.electronwill.night-config:core:3.8.1")
    implementation include("com.electronwill.night-config:toml:3.8.1")

//    modCompileOnly "me.shedaniel:RoughlyEnoughItems-api-fabric:${rei_version}"
//    modCompileOnly "me.shedaniel:RoughlyEnoughItems-fabric:${rei_version}"

    compileOnly("mezz.jei:jei-26.1-snapshot-4-common-api:${jei_version}")
    compileOnly("mezz.jei:jei-26.1-snapshot-4-fabric:${jei_version}")

//    compileOnly "maven.modrinth:cobblemon:1.7.1-fabric,1.21.1"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 25
}

java {
	withSourcesJar()

	sourceCompatibility = JavaVersion.VERSION_25
	targetCompatibility = JavaVersion.VERSION_25
}

jar {
	inputs.property "archivesName", project.base.archivesName

	from("LICENSE") {
		rename { "${it}_${inputs.properties.archivesName}"}
	}
}

loom {
    accessWidenerPath = file("src/main/resources/easybrewing.classtweaker")
}

// configure the maven publication
publishing {
	publications {
		create("mavenJava", MavenPublication) {
			artifactId = project.archives_base_name
			from components.java
		}
	}

	repositories {
	}
}

publishMods {
    file.set(jar.archiveFile)
    type = BETA
    modLoaders.add("fabric")
    changelog = file("changelog.md").text
    displayName = "easybrewing-" + mod_version

    curseforge {
        projectId = "1405256"
        accessToken = findProperty("CF_TOKEN")
        minecraftVersions.add("26.1-snapshot")
    }

    modrinth {
        projectId = 'DusK80tO'
        accessToken = findProperty("MODRINTH_TOKEN")
        minecraftVersions.add(minecraft_version)
    }
}